# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: 
      - "main"
      - "markus"
      - "*"
  pull_request:
    branches: 
      -  "main" 
      - "markus"
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: sqtest

    env:
      VERSION: "0.0.1"

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Build the project using Gradle
      - name: Run Gradle Build
        run: | 
          docker run --rm -v "$PWD":/home/gradle/project -w /home/gradle/project gradle:jdk17 gradle build
          
      # Ensure permissions are correct (if needed)
      - name: Adjust permissions
        run: | 
          docker run --rm -v "$PWD":/project bash:latest chown --recursive $(id -u):$(id -g) /project
          
      # Check Gradle version (using gradle:jdk17 instead of my-gradle-app)
      - name: Check Gradle version
        run: |
          docker run --rm gradle:jdk17 gradle -v
        
# Build Docker image using Amazon Corretto
      - name: Build Docker using Amazon Corretto
        run: |
          echo 'FROM amazoncorretto:17' > Dockerfile.temp
          echo 'COPY build/libs/Devops_project-0.0.1-SNAPSHOT.jar /app.jar' >> Dockerfile.temp
          echo 'ENTRYPOINT ["java", "-jar", "/app.jar"]' >> Dockerfile.temp
          docker build -t 5.75.241.180:5000/myapp:${{ env.VERSION }} -f Dockerfile.temp .
          rm Dockerfile.temp


      # Push Docker image to internal registry
      - name: Push Docker Image
        run: |
          docker push 5.75.241.180:5000/myapp:${{env.VERSION}}

      # Run SonarQube 
      - name: Run SonarQube Scan
        run: |
            docker run \
            --rm \
            -v "$PWD:/usr/src" \
            -e "SONAR_SCANNER_OPTS=-Dsonar.host.url=https://sonarqube.goa.systems -Dsonar.token=sqp_016fff0e633a7414b3f7471c39459d6d75bce059 -Dsonar.projectKey=team1 -Dsonar.sources=src/main/java -Dsonar.qualitygate.wait=true" \
            --network host \
            sonarsource/sonar-scanner-cli:10

      #Setup SSH Key for Deployment
      - name: Setup SSH Key for Deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SHH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      #Deploy to the Production Server
      - name: Deploy to Production Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no production@5.75.241.180 '
          docker stop myapp || true && docker rm myapp || true;
          docker pull 5.75.241.180:5000/myapp:${{ env.VERSION }};
          docker run -d --name myapp -p 8080:8080 5.75.241.180:5000/myapp:${{ env.VERSION }};
          '
            
      #Generate a pdf from the README.md file
      - name: Generate pdf using pandoc
        run: |
          docker run --rm \
          --volume "$(pwd):/data" \
          --user $(id -u):$(id -g) \
          pandoc/extra README.md -o README.pdf --template=template.tex --pdf-engine=luaotfload


      # Generate HTML documentation
      - name: Generate HTML Documentation
        run: |
          docker run --rm -v "$PWD:/docs" squidfunk/mkdocs-material build


      # Build and Push Documentation Container
      - name: Build and Push Documentation Container
        run: |
          docker build -t 5.75.241.180:5000/documentation:${{ env.VERSION }} -f Documentation.dockerfile .
          docker push 5.75.241.180:5000/documentation:${{ env.VERSION }}

      # Deploy to Production Server
      - name: Deploy Documentation to Production Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@10.0.40.163 '
            docker pull 5.75.241.180:5000/documentation:${{ env.VERSION }};
            docker stop documentation || true && docker rm documentation || true;
            docker run -d --name documentation -p 8081:80 5.75.241.180:5000/documentation:${{ env.VERSION }};
          '
        
        


        

          





